#!/usr/bin/env python3
"""Turn runs/eval/results.json into the LaTeX the report reads.

    python scripts/make_tables.py --results runs/eval/results.json

Emits into report/tables/:

  baselines.tex   single-recaller baselines
  ablations.tex   one knob off at a time
  genre.tex       per-genre breakdown
  numbers.tex     \\newcommand macros for every number quoted in prose

The macros exist so that no figure is typed into the paper by hand. If a run
changes, the prose changes with it or the build fails on an undefined macro,
which is the only reliable way to keep a results section honest.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROWS_BASELINE = ["gazetteer", "chunker-gated", "chunker", "cvalue", "union"]
ROWS_ABLATION = ["full", "-negative", "-consensus", "-verifier", "-abstention", "-structure"]

PRETTY = {
    "gazetteer": "CSO gazetteer",
    "chunker-gated": "Chunker (lexicon-gated)",
    "chunker": "Chunker (open)",
    "cvalue": "C-value/NC-value",
    "union": "Union of recallers",
    "full": r"\textsc{Tekne}",
    "-negative": r"\quad $-$ negative lexicon",
    "-consensus": r"\quad $-$ consensus",
    "-verifier": r"\quad $-$ verifier",
    "-abstention": r"\quad $-$ abstention",
    "-structure": r"\quad $-$ KB \& abbreviations",
}


def load(path: Path) -> dict[str, dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {c["name"]: c for c in payload["conditions"]}


def table(conditions: dict[str, dict], order: list[str], caption_rule: int | None = None) -> str:
    lines = [
        "% generated by scripts/make_tables.py -- do not edit",
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        r" & \multicolumn{3}{c}{Strict} & \multicolumn{1}{c}{Partial} & & \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-5}",
        r"System & P & R & F$_1$ & F$_1$ & Type & AURC \\",
        r"\midrule",
    ]
    for i, name in enumerate(order):
        row = conditions.get(name)
        if row is None:
            continue
        m = row["metrics"]
        s, p = m["strict"], m["partial"]
        lines.append(
            f"{PRETTY.get(name, name)} & {s['precision']:.3f} & {s['recall']:.3f} & "
            f"{s['f1']:.3f} & {p['f1']:.3f} & {m['type_accuracy']:.3f} & "
            f"{row['selective']['aurc']:.3f} \\\\"
        )
        if caption_rule is not None and i == caption_rule:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def genre_table(conditions: dict[str, dict]) -> str:
    full = conditions.get("full")
    if not full:
        return "% no `full` condition in results\n"
    per_genre = full["metrics"]["per_genre"]
    lines = [
        "% generated by scripts/make_tables.py -- do not edit",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Genre & P & R & F$_1$ & Gold \\",
        r"\midrule",
    ]
    for genre in ("paper", "patent"):
        row = per_genre.get(genre)
        if not row:
            continue
        lines.append(
            f"{genre.capitalize()}s & {row['precision']:.3f} & {row['recall']:.3f} & "
            f"{row['f1']:.3f} & {row['tp'] + row['fn']} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def macros(conditions: dict[str, dict], extra: dict[str, str]) -> str:
    out = ["% generated by scripts/make_tables.py -- do not edit"]

    def emit(name: str, value: str) -> None:
        out.append(rf"\newcommand{{\{name}}}{{{value}}}")

    for key, row in conditions.items():
        tag = _macro_name(key)
        m = row["metrics"]
        emit(f"{tag}P", f"{m['strict']['precision']:.3f}")
        emit(f"{tag}R", f"{m['strict']['recall']:.3f}")
        emit(f"{tag}F", f"{m['strict']['f1']:.3f}")
        emit(f"{tag}PF", f"{m['partial']['f1']:.3f}")
        emit(f"{tag}Type", f"{m['type_accuracy']:.3f}")
        emit(f"{tag}Halluc", f"{m['hallucination_rate']:.3f}")
        emit(f"{tag}Aurc", f"{row['selective']['aurc']:.3f}")
        emit(f"{tag}Ece", f"{row['selective']['ece']:.3f}")
        cov = row["selective"].get("coverage_at_90_precision")
        emit(f"{tag}CovNinety", f"{cov:.3f}" if cov is not None else "--")
        emit(f"{tag}Seconds", f"{row['seconds']:.0f}")

    for name, value in extra.items():
        emit(name, value)
    return "\n".join(out) + "\n"


def _macro_name(key: str) -> str:
    """LaTeX macro names must be letters only."""
    cleaned = key.replace("-", "No").replace("_", "")
    cleaned = re.sub(r"[^A-Za-z]", "", cleaned)
    return "R" + cleaned[0].upper() + cleaned[1:]


def corpus_numbers(gold_path: Path) -> dict[str, str]:
    if not gold_path.is_file():
        return {}
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    from tekne.eval.gold import read_gold

    gold = read_gold(gold_path)
    papers = [g for g in gold.values() if g.genre.value == "paper"]
    patents = [g for g in gold.values() if g.genre.value == "patent"]
    mentions = [m for g in gold.values() for m in g.mentions]
    by_type: dict[str, int] = {}
    for m in mentions:
        by_type[m.type.value] = by_type.get(m.type.value, 0) + 1
    tracked = sum(by_type.get(t, 0) for t in ("artifact", "method", "material"))
    return {
        "NumDocs": str(len(gold)),
        "NumPapers": str(len(papers)),
        "NumPatents": str(len(patents)),
        "NumGold": str(len(mentions)),
        "NumGoldTracked": str(tracked),
        "NumGoldPaper": str(sum(len(g.mentions) for g in papers)),
        "NumGoldPatent": str(sum(len(g.mentions) for g in patents)),
        "PctArtifact": f"{100 * by_type.get('artifact', 0) / max(len(mentions), 1):.0f}",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="runs/eval/results.json")
    parser.add_argument("--gold", default="data/gold/gold.jsonl")
    parser.add_argument("--out", default="report/tables")
    args = parser.parse_args()

    conditions = load(Path(args.results))
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    (out / "baselines.tex").write_text(table(conditions, ROWS_BASELINE), encoding="utf-8")
    (out / "ablations.tex").write_text(
        table(conditions, ROWS_ABLATION, caption_rule=0), encoding="utf-8"
    )
    (out / "genre.tex").write_text(genre_table(conditions), encoding="utf-8")
    (out / "numbers.tex").write_text(
        macros(conditions, corpus_numbers(Path(args.gold))), encoding="utf-8"
    )

    print(f"wrote {len(list(out.glob('*.tex')))} files to {out}")
    for name in sorted(conditions):
        m = conditions[name]["metrics"]
        print(f"  {name:16} F1={m['strict']['f1']:.3f} partial={m['partial']['f1']:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
