#!/usr/bin/env python3
"""Turn runs/eval/results.json into the LaTeX the report reads.

    python scripts/make_tables.py --results runs/eval/results.json

Emits into report/tables/:

  results.tex     baselines and ablations in one table
  selective.tex   the selective-prediction numbers
  genre.tex       per-genre breakdown
  numbers.tex     \\newcommand macros for every number quoted in prose

The macros exist so that no figure is typed into the paper by hand. If a run
changes, the prose changes with it or the build fails on an undefined macro,
which is the only reliable way to keep a results section honest.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROWS_BASELINE = ["gazetteer", "chunker-gated", "chunker", "cvalue", "union"]
ROWS_ABLATION = ["full", "-negative", "-consensus", "-verifier", "-abstention", "-structure"]

PRETTY = {
    "gazetteer": "CSO gazetteer",
    "chunker-gated": "Chunker (gated)",
    "chunker": "Chunker (open)",
    "cvalue": "C-value/NC-value",
    "union": "Union, no guards",
    "full": r"\textsc{Tekne}",
    "-negative": r"\;$-$ negative lexicon",
    "-consensus": r"\;$-$ consensus",
    "-verifier": r"\;$-$ verifier",
    "-abstention": r"\;$-$ abstention",
    "-structure": r"\;$-$ KB, abbrev.",
}


def load(path: Path) -> dict[str, dict]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {c["name"]: c for c in payload["conditions"]}


def results_table(conditions: dict[str, dict]) -> str:
    """One table for both suites, separated by a rule.

    Two suites in two tables made the reader flip between them to answer the
    question they actually have, which is where the full system sits relative to
    its own parts. Strict and partial matching get three columns each because the
    gap between them is the boundary-disagreement signal, not noise.
    """
    lines = [
        "% generated by scripts/make_tables.py -- do not edit",
        r"\begin{tabular}{@{}l rrr rrr rr r@{}}",
        r"\toprule",
        r"& \multicolumn{3}{c}{Strict match} & \multicolumn{3}{c}{Partial match}"
        r" & \multicolumn{2}{c}{Labels} & \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-9}",
        r"System & P & R & F$_1$ & P & R & F$_1$ & Type & Role & AURC \\",
        r"\midrule",
        r"\multicolumn{10}{@{}l}{\itshape Single-recaller baselines"
        r" (guards reduced to grounding)} \\",
    ]

    def row(name: str) -> str | None:
        item = conditions.get(name)
        if item is None:
            return None
        m = item["metrics"]
        st, pt = m["strict"], m["partial"]
        return (
            f"{PRETTY.get(name, name)} & {st['precision']:.3f} & {st['recall']:.3f} & "
            f"{st['f1']:.3f} & {pt['precision']:.3f} & {pt['recall']:.3f} & {pt['f1']:.3f} & "
            f"{m['type_accuracy']:.3f} & {m['role_accuracy']:.3f} & "
            f"{item['selective']['aurc']:.3f} \\\\"
        )

    for name in ROWS_BASELINE:
        line = row(name)
        if line:
            lines.append(line)

    lines.append(r"\midrule")
    lines.append(r"\multicolumn{10}{@{}l}{\itshape Full pipeline and ablations} \\")
    for name in ROWS_ABLATION:
        line = row(name)
        if line:
            lines.append(line)

    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def selective_table(conditions: dict[str, dict]) -> str:
    """The numbers a corpus operator actually picks a threshold from."""
    lines = [
        "% generated by scripts/make_tables.py -- do not edit",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"System & AURC & ECE & P@50\% \\",
        r"\midrule",
    ]
    for name in ("full", "-verifier", "-negative", "union"):
        item = conditions.get(name)
        if item is None:
            continue
        sel = item["selective"]
        at50 = sel.get("precision_at_50_coverage")
        lines.append(
            f"{PRETTY.get(name, name)} & {sel['aurc']:.3f} & {sel['ece']:.3f} & "
            f"{at50:.3f} \\\\" if at50 is not None else
            f"{PRETTY.get(name, name)} & {sel['aurc']:.3f} & {sel['ece']:.3f} & -- \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def genre_table(conditions: dict[str, dict]) -> str:
    """Per-genre performance of the full system.

    Reported separately because patents supply 62% of the gold mentions from 45%
    of the documents -- claim language repeats component names -- so a pooled
    figure is mostly a patent figure.
    """
    full = conditions.get("full")
    if not full:
        return "% no `full` condition in results\n"
    per_genre = full["metrics"]["per_genre"]
    lines = [
        "% generated by scripts/make_tables.py -- do not edit",
        r"\begin{tabular}{@{}lrrrrr@{}}",
        r"\toprule",
        r"Genre & Docs & Gold & P & R & F$_1$ \\",
        r"\midrule",
    ]
    counts = {"paper": 24, "patent": 20}
    for genre in ("paper", "patent"):
        row = per_genre.get(genre)
        if not row:
            continue
        lines.append(
            f"{genre.capitalize()}s & {counts.get(genre, '--')} & {row['tp'] + row['fn']} & "
            f"{row['precision']:.3f} & {row['recall']:.3f} & {row['f1']:.3f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def macros(conditions: dict[str, dict], extra: dict[str, str]) -> str:
    out = ["% generated by scripts/make_tables.py -- do not edit"]

    def emit(name: str, value: str) -> None:
        out.append(rf"\newcommand{{\{name}}}{{{value}}}")

    for key, row in conditions.items():
        tag = _macro_name(key)
        m = row["metrics"]
        emit(f"{tag}P", f"{m['strict']['precision']:.3f}")
        emit(f"{tag}R", f"{m['strict']['recall']:.3f}")
        emit(f"{tag}F", f"{m['strict']['f1']:.3f}")
        emit(f"{tag}PF", f"{m['partial']['f1']:.3f}")
        emit(f"{tag}Type", f"{m['type_accuracy']:.3f}")
        emit(f"{tag}Halluc", f"{m['hallucination_rate']:.3f}")
        emit(f"{tag}Aurc", f"{row['selective']['aurc']:.3f}")
        emit(f"{tag}Ece", f"{row['selective']['ece']:.3f}")
        cov = row["selective"].get("coverage_at_90_precision")
        emit(f"{tag}CovNinety", f"{cov:.3f}" if cov is not None else "--")
        emit(f"{tag}Seconds", f"{row['seconds']:.0f}")

    for name, value in extra.items():
        emit(name, value)
    return "\n".join(out) + "\n"


def _macro_name(key: str) -> str:
    """LaTeX macro names must be letters only, so build CamelCase ones.

    ``full`` -> ``RFull``; ``-verifier`` -> ``RNoVerifier``;
    ``chunker-gated`` -> ``RChunkerGated``.
    """
    ablation = key.startswith("-")
    parts = [p for p in re.split(r"[-_\s]+", key) if p]
    camel = "".join(p[0].upper() + p[1:] for p in parts)
    camel = re.sub(r"[^A-Za-z]", "", camel)
    return "R" + ("No" if ablation else "") + camel


def corpus_numbers(gold_path: Path) -> dict[str, str]:
    if not gold_path.is_file():
        return {}
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    from tekne.eval.gold import read_gold

    gold = read_gold(gold_path)
    papers = [g for g in gold.values() if g.genre.value == "paper"]
    patents = [g for g in gold.values() if g.genre.value == "patent"]
    mentions = [m for g in gold.values() for m in g.mentions]
    by_type: dict[str, int] = {}
    for m in mentions:
        by_type[m.type.value] = by_type.get(m.type.value, 0) + 1
    tracked = sum(by_type.get(t, 0) for t in ("artifact", "method", "material"))
    return {
        "NumDocs": str(len(gold)),
        "NumPapers": str(len(papers)),
        "NumPatents": str(len(patents)),
        "NumGold": str(len(mentions)),
        "NumGoldTracked": str(tracked),
        "NumGoldPaper": str(sum(len(g.mentions) for g in papers)),
        "NumGoldPatent": str(sum(len(g.mentions) for g in patents)),
        "PctArtifact": f"{100 * by_type.get('artifact', 0) / max(len(mentions), 1):.0f}",
    }


def error_numbers(path: Path) -> dict[str, str]:
    """Macros for the stage-wise error analysis and the head-noun gating claim.

    These were typed into the report by hand, which is how the gating figure went
    stale: it was measured before the gold set was corrected and the span lattice
    widened, and it understated the effect by eleven points. Anything quoted in
    prose now comes from a file the evaluation writes.
    """
    if not path.is_file():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, str] = {"ErrScored": str(payload.get("gold_scored", 0))}
    names = {
        "emitted": "ErrEmitted",
        "withheld": "ErrWithheld",
        "lost_at_decode": "ErrDecode",
        "rejected": "ErrRejected",
        "never_proposed": "ErrNeverProposed",
        "wrong_type": "ErrWrongType",
    }
    for key, macro in names.items():
        row = payload.get("outcomes", {}).get(key)
        if row:
            out[macro] = f"{row['share'] * 100:.1f}"
    coverage = payload.get("recall_stage_coverage") or {}
    if coverage:
        out["GateDrops"] = f"{coverage['dropped_by_gate'] * 100:.0f}"
        out["CoverageOpen"] = f"{coverage['open'] * 100:.1f}"
        out["CoverageGated"] = f"{coverage['gated'] * 100:.1f}"
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="runs/eval/results.json")
    parser.add_argument("--gold", default="data/gold/gold.jsonl")
    parser.add_argument("--errors", default="runs/eval/error_analysis.json")
    parser.add_argument("--out", default="report/tables")
    args = parser.parse_args()

    conditions = load(Path(args.results))
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    (out / "results.tex").write_text(results_table(conditions), encoding="utf-8")
    (out / "selective.tex").write_text(selective_table(conditions), encoding="utf-8")
    (out / "genre.tex").write_text(genre_table(conditions), encoding="utf-8")
    extra = corpus_numbers(Path(args.gold))
    extra.update(error_numbers(Path(args.errors)))
    (out / "numbers.tex").write_text(macros(conditions, extra), encoding="utf-8")

    print(f"wrote {len(list(out.glob('*.tex')))} files to {out}")
    for name in sorted(conditions):
        m = conditions[name]["metrics"]
        print(f"  {name:16} F1={m['strict']['f1']:.3f} partial={m['partial']['f1']:.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
